# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack_Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
