# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0002_attack_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense_node',
            name='parent',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='GUI.Attack_Node'),
        ),
    ]
