# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0004_auto_20170916_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defense_node',
            options={'ordering': ['parent']},
        ),
        migrations.AddField(
            model_name='defense_node',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
