# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0006_auto_20170920_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('parent', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='GUI.Defense_Node')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
