# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
    ]
